# Generated by Django 3.0.7 on 2021-01-15 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('about', models.CharField(max_length=200, null=True)),
                ('profileimage', models.ImageField(blank=True, default='proerror.png', null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('cost', models.FloatField(null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('time', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('detail', models.CharField(max_length=500, null=True)),
                ('p1', models.ImageField(blank=True, default='dftimg.png', null=True, upload_to='')),
                ('p2', models.ImageField(blank=True, default='dftimg.png', null=True, upload_to='')),
                ('p3', models.ImageField(blank=True, default='dftimg.png', null=True, upload_to='')),
                ('p4', models.ImageField(blank=True, default='dftimg.png', null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/media/%y')),
                ('dop', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
