# Generated by Django 3.0.7 on 2021-01-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0002_auto_20210116_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
