# Generated by Django 3.0.7 on 2021-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0004_auto_20210117_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(blank=True, default='proerror.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Profileimage',
        ),
    ]
