# Generated by Django 3.0.7 on 2021-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0005_auto_20210117_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('Book', 'Book'), ('Electronic', 'Electronic'), ('Vehical', 'Vehical'), ('Furniture', 'Furniture')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='detail',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
